### ISSUE TITLE
Docker worker image not running

### ISSUE THREAD

**Issue by cucumber-turtle** [jerlendds/osintbuddy#17]
**Bug description**
The docker worker is not running and exiting with code 127. The error shown is `/usr/bin/env: ‘bash\r’: No such file or directory`

This seems to only happen on Windows environments. 

**To Reproduce**
1. In a Windows environment, clone the repository. Make sure autocrlf on git is set to false.
2. Run the docker daemon with WSL2.
3. Start the stack with docker.
4. You will get the error:
![image](https://user-images.githubusercontent.com/66296587/219847995-cb3261e8-6a9f-4a98-b6a4-c4e1a3dd81e2.png)
And the image will attempt to restart repeatedly.

**Expected behavior**
All scripts should run without the trailing \r character and the image should be running after the stack is started successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/66296587/219848386-fd34f7ee-5ed1-45b0-84e5-b40ecd769bc9.png)

**Desktop:**
 - OS: Windows 11

**Additional context**
I made sure .env uses LF instead of CRLF as it is the only file I modified from the main branch. 
Previously start-reload.sh was also not found but I fixed that by setting git's autocrlf setting to false and then re-cloning the repository. 
I changed wsl.conf to have the following configuration:
```
[interop]
appendWindowsPath = false
```

But the error persists.

**Comment by jerlendds** [comment]
Hi, please see: https://askubuntu.com/questions/1148263/r-added-end-of-the-script-command

ensure you use the correct line ending
