### ISSUE TITLE
Docker-composer Error

### ISSUE THREAD

**Issue by meetgyn** [jerlendds/osintbuddy#21]
**Is your feature request related to a problem? Please describe.**
When running docker-compose up program returns an error and does not upload the image

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/3695608/224319913-25d0350d-17b0-4a3f-8f6d-30c78294e123.png)

**Additional context**
I made a copy of .env.example to .env and even so the image did not upload

**Comment by jerlendds** [comment]
Hey, thanks for bringing this up!  Ill take a look at this on the weekend and I'll post an update here once I finish that

**Comment by SteveGremory** [comment]
did you perhaps run `docker compose down`?

**Comment by jerlendds** [comment]
@meetgyn I've uploaded the worker, backend, and microservice images to the docker registry, try pulling the changes and images and running again
