### ISSUE TITLE
Missing LICENSE definition

### ISSUE THREAD

**Issue by bugfest** [jerlendds/osintbuddy#36]
**Describe the bug**
Missing LICENSE file

**To Reproduce**
N/A

**Expected behavior**
Find a license (MIT, Apache, GPL,... ) definition at https://github.com/jerlendds/osintbuddy/blob/main/LICENSE

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
A license is required for some individuals or companies to decide whether they can use and eventually contribute to the project

**Comment by jerlendds** [comment]
License has been added, thanks for noticing that
