### ISSUE TITLE
frontend: Record inputs get removed when clicking outside

### ISSUE THREAD

**Issue by bugfest** [jerlendds/osintbuddy#43]
**Describe the bug**

**To Reproduce**
1. Go to http://localhost:3000/app/dashboard. Create a new investigation
2. Create a record (any type)
3. Write some text in the input field
4. Click anywhere outside the record (within the investigation canvas: react flow pane)
5. The input gets wiped

**Expected behavior**
The input should not change without the user editing it

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 934933f31fc20a927556a853367360f3f4139880

**Additional context**
n/a

**Comment by jerlendds** [comment]
Will be fixed with this PR: https://github.com/jerlendds/osintbuddy/issues/39

**Comment by bugfest** [comment]
> Will be fixed with this issue: #39

Great to know it's in your radar. Please close this issue if you feel it's duplicated

**Comment by jerlendds** [comment]
Slightly improved now, rest of the fix will come with the other issue ![osintbuddy-demo](https://github.com/jerlendds/osintbuddy/assets/29207058/5f4aae3f-1a4d-4732-8846-1c8c0877cbea)
