### ISSUE TITLE
[BUG] Connection to external interface fails: "We ran into an error fetching your projects"

### ISSUE THREAD

**Issue by MDIMANNO** [jerlendds/osintbuddy#46]
Connection on localhost:3000 interface
     - Creating a new project, it works, perfect
     
Connection to external interface (ens33): 192.168.1.100:3000
    - Backend is reported as not running
    - Not working

Test solutions: 

     - Modify DOMAIN in .env file (192.168.1.100)
     - Change backend port in docker-compose.yml (5000:5000) 
None of these solutions solved the bug

**Screenshots**
![image](https://github.com/jerlendds/osintbuddy/assets/48934174/523b3f95-cd89-4bee-ad15-6cf3a8788636)

**Desktop (please complete the following information):**
 - OS: Debian10/11
 - Browser Firefox/Edge/Brave
 - Version latest

**Comment by jerlendds** [comment]
Thanks for reporting this! I'll look into this and get back to you soon

**Comment by jerlendds** [comment]
Hey @MDIMANNO , I'd need to see the client side error to be sure but I suspect this might be a CORs issue, can you try updating the `BACKEND_CORS_ORIGINS` in the `.env` file with the following values?

```
BACKEND_CORS_ORIGINS='["192.168.1.100:3000","http://localhost:3000","http://localhost",]'

```

**Comment by MDIMANNO** [comment]
Hello, still the same error now, it doesn't work on localhost nor on the external interface
I always get the same error

**Comment by jerlendds** [comment]
> Hello, still the same error now, it doesn't work on localhost nor on the external interface I always get the same error

Ahh that is not good, can you open the dev tools in the browser, `CTRL+SHIFT+I`, and send me a copy of the error message that shows up in the console?

**Comment by MDIMANNO** [comment]
Tanks, the new release work, I just changed the domain to my interface and the same with BACKEND_CORS_ORIGINS
