### ISSUE TITLE
[BUG] Consistency between README and main website + No module named 'jaydebeapi' error

### ISSUE THREAD

**Issue by make-believe-agency** [jerlendds/osintbuddy#47]
**Describe the bug**
Consistency

**To Reproduce**
1. Attempt install

**Expected behavior**
Installation to work, and instructions to be consistent in all available locations.

**Screenshots**
- N/A

**Desktop (please complete the following information):**
 - N/A

**Additional context**
Latest version doesn't install and instructions are incorrect on main website

**Comment by make-believe-agency** [comment]
[![asciicast](https://asciinema.org/a/590722.svg)](https://asciinema.org/a/590722)

**Comment by jerlendds** [comment]
Thanks for catching that, I forgot to update the docs site but I'll get that done within the week! 
An update has been pushed and the installation should now work. I'll make sure to double check my commits next time to make sure no changes from my other branches get into main until they're ready

**Comment by jerlendds** [comment]
Installation docs have been updated: https://docs.osintbuddy.com/docs/installation
