### ISSUE TITLE
CSE Search Entity Bad Request

### ISSUE THREAD

**Issue by derekburgess** [jerlendds/osintbuddy#51]
The CSE Search list is very long, making it hard for me to tell which ones might work or I could be selecting known broken searches... Either way, I have tested this with 10 randomly selected searches from the list, using the same query and page request. All result in a frontend error, "There was an error fetching CSE results. Please try again."

- GEOSINTsearch (Selected because it was the default choice and I assumed it worked).
- Social Search (Sounded generic enough)
- TikTok Search Engine
- Linkedin People Search
- Linkedin
- Image Search
- Github Search +
- Twitter Historical Search
- Twitter CSE
- 300+ Social Networking Sites

This list is not a request to fix those searches, I selected them at random.

In addition to that error, the console shows:
```
osintbuddy-backend-1       | plugin instance:  <app.plugins.cse.CSESearchPlugin object at 0x7f82da07ee10>
osintbuddy-backend-1       | resp:  <Response [200 OK]>
osintbuddy-backend-1       | INFO:     172.18.0.1:38180 - "GET /api/v1/nodes/transforms?node_type=CSE%20Search HTTP/1.1" 200 OK
osintbuddy-microservice-1  | Crawling results for:  001794496531944888666:iyxger-cwug{"time":"2023-06-13T12:04:23.529339569Z","id":"","remote_ip":"172.18.0.2","host":"microservice:1323","method":"GET","uri":"/google-cse?query=Elon%20Musk&pages=1&id=001794496531944888666%3Aiyxger-cwug","user_agent":"python-httpx/0.24.0","status":200,"error":"","latency":3000179116,"latency_human":"3.000179116s","bytes_in":0,"bytes_out":5}
osintbuddy-microservice-1  | 2023/06/13 12:04:23 Something went wrong: Bad Request
```
It appears the initial request/response is successful, but microservices fails to handle the data? or the data is returned malformed?

**Comment by derekburgess** [comment]
Thank you! I just started learning Go, so I'm curious to see your fix.

**Comment by jerlendds** [comment]
No problem! I've just pushed the change, you can check it out [here](https://github.com/jerlendds/osintbuddy/commit/ce8e97a77aba11f98065860efe481fb96302d7d1#diff-40c962489e6c74cfec4390a325368e3ed1d247464e2165dd5b5d389af2051e9e) if you'd like. 

[commit ce8e97a](https://github.com/jerlendds/osintbuddy/commit/ce8e97a77aba11f98065860efe481fb96302d7d1)

![fix-cse-queryencoding](https://github.com/jerlendds/osintbuddy/assets/29207058/778f16d8-bdac-4c5a-8945-f0b21a5307e7)
