### ISSUE TITLE
[BUG] Projects not saved?

### ISSUE THREAD

**Issue by nono2357** [jerlendds/osintbuddy#52]
Projects don't seem to be saved.

**Expected behavior**
Projects should be saved either automatically or by clicking on a button.

 - OS: Ubuntu 22.04.2 LTS
 - Browser: Brave stable 1.42.88
 - Version commit 16073e184a5d2873567cdd94c2e754e3843cc5de

**Comment by jerlendds** [comment]
That's a known issue, I'm working on integrating JanusGraph + ScyllaDB today to enable saving nodes. If that's not fully implemented this weekend then expect saving to be here by next week

**Comment by jerlendds** [comment]
Update:
I'm currently working with some people from the JanusGraph team as I've been unable to use the DynamicGraphs feature as they've documented (basically creating a new graph db like a SQL `CREATE DATABASE`) . (https://github.com/jerlendds/janus-dynamicgraphs-bug). Once a solution can be found I'll be able to push the rest of this update

**Comment by jerlendds** [comment]
This is now implemented in the develop branch. Some plugin transforms may not work as they need to be refactored but once that's fixed up this will be merged into `main`. Make sure to rebuild your images to test out the latest changes: `docker compose build`
