### ISSUE TITLE
[BUG] BASE_URL is permanently set to localhost:8000

### ISSUE THREAD

**Issue by HeroesLament** [jerlendds/osintbuddy#54]
**Describe the bug**
In the application, there seems to be no way to set the FastAPI BASE_URL to anything other than localhost:8000.

**To Reproduce**
Set .env to desired values:
```ENVIRONMENT=production
BASE_URL=http://100.108.63.94:8000
```
**Expected behavior**
The baseURL should become http://100.108.63.94:8000.

**Screenshots**
![875](https://github.com/jerlendds/osintbuddy/assets/6320437/e848e917-2c4d-4bbb-a6c6-fb2deb655cc9)

**Desktop (please complete the following information):**
 - OS: Garuda Linux
 - Browser ungoogled-chromium
 - Version 114.0.5735.198 (Official Build, ungoogled-chromium) Arch Linux (64-bit)

**Additional context**
We should consider adding logic to https://github.com/jerlendds/osintbuddy/blob/6dfe6f3f20e11588eb40782a54f4929ea6338217/frontend/src/services/api.service.ts#L5 to first determine if it is development vs production, and if production, the BASE_URL should be parsed and inserted into the REACT_APP_BASE_URL environment variable. 

Alternatively, we could just add  REACT_APP_BASE_URL and NODE_ENV directly into the .env file. I added them, duplicated the values, executed "docker-compose build", and then "docker-compose up -d", and the baseURL became properly set.

Let me know your thoughts.

**Comment by jerlendds** [comment]
Thanks for the fix! ( PR https://github.com/jerlendds/osintbuddy/pull/55 )
