### ISSUE TITLE
[BUG] Janus not starting

### ISSUE THREAD

**Issue by smfai200** [jerlendds/osintbuddy#56]
osintbuddy-janus-1  | exec /usr/local/bin/docker-entrypoint.sh: no such file or directory

**Comment by jerlendds** [comment]
Without more details or logs this cannot be debugged or looked into.

@smfai200 Please provide details and some context or this will be closed. For anyone else browsing this, there is a known issue that was introduced recently that causes the UI to fail to start if you're not in a `production` `.env` like so:  `ENVIRONMENT=production`

**Comment by smfai200** [comment]
Hi, Sorry for that. When i run the docker compose up, all processes start without any issue but the Janus Container doesn't start which causes the application to breakdown and the logs just show 
osintbuddy-janus-1 | exec /usr/local/bin/docker-entrypoint.sh: no such file or directory

Although i confirmed from the terminal that the file does exists and is copied

**Comment by jerlendds** [comment]
What is your operating system and can you show me the complete logs from the application when JanusGraph fails to start? 

You can also try modifying the `janus/janusgraph.Dockerfile` file on `line 70` to look like: 

`ENTRYPOINT [ "/usr/local/bin/docker-entrypoint.sh" ]`

**Comment by smfai200** [comment]
The issue is resolved with the updated .env

**Comment by jerlendds** [comment]
Thanks for reporting back!
